# JS_AUSTENITE_APP_NAME is the name of the app for which Austenite documentation
# is generated.
ifndef JS_AUSTENITE_APP_NAME
$(error "JS_AUSTENITE_APP_NAME must be defined in the project's Makefile.")
endif

# JS_AUSTENITE_APP_CMD is the command to run the app for which Austenite
# documentation is generated.
ifndef JS_AUSTENITE_APP_CMD
$(error "JS_AUSTENITE_APP_CMD must be defined in the project's Makefile.")
endif

# JS_AUSTENITE_MARKDOWN_FILE is the name of the file containing the
# documentation generated by Austenite.
JS_AUSTENITE_MARKDOWN_FILE ?= ENVIRONMENT.md

# JS_AUSTENITE_REQ is a space-separated list of prerequisites needed to generate
# the Austenite documentation.
JS_AUSTENITE_REQ += artifacts/link-dependencies.touch

################################################################################

GENERATED_FILES += $(JS_AUSTENITE_MARKDOWN_FILE)

$(JS_AUSTENITE_MARKDOWN_FILE): $(JS_AUSTENITE_REQ)
	AUSTENITE_MODE=usage/markdown AUSTENITE_APP="$(JS_AUSTENITE_APP_NAME)" $(JS_AUSTENITE_APP_CMD) > "$@"
