// Code generated by protoc-gen-go. DO NOT EDIT.
// source: .makefiles/go1/make-go1-1/source.proto

package go1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage struct {
	Any                  *any.Any `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1351a5b5bb019b7a, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetAny() *any.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "TestMessage")
}

func init() {
	proto.RegisterFile(".makefiles/go1/make-go1-1/source.proto", fileDescriptor_1351a5b5bb019b7a)
}

var fileDescriptor_1351a5b5bb019b7a = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xd3, 0xcb, 0x4d, 0xcc,
	0x4e, 0x4d, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x4f, 0xcf, 0x37, 0xd4, 0x07, 0xf1, 0x74, 0xd3, 0xf3,
	0x0d, 0x75, 0x0d, 0xf5, 0x8b, 0xf3, 0x4b, 0x8b, 0x92, 0x53, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0xa5, 0x24, 0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xbc, 0xa4, 0xd2, 0x34, 0xfd, 0xc4,
	0xbc, 0x4a, 0x88, 0x94, 0x92, 0x29, 0x17, 0x77, 0x48, 0x6a, 0x71, 0x89, 0x6f, 0x6a, 0x71, 0x71,
	0x62, 0x7a, 0xaa, 0x90, 0x1a, 0x17, 0x73, 0x62, 0x5e, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7,
	0x91, 0x88, 0x1e, 0x44, 0x9f, 0x1e, 0x4c, 0x9f, 0x9e, 0x63, 0x5e, 0x65, 0x10, 0x48, 0x81, 0x13,
	0x6b, 0x14, 0x73, 0x7a, 0xbe, 0x61, 0x12, 0x1b, 0x58, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x43, 0x07, 0x5a, 0xac, 0x89, 0x00, 0x00, 0x00,
}
