# GO_FERRITE_MARKDOWN_FILE is the name of the file containing the documentation
# generated by Ferrite.
GO_FERRITE_MARKDOWN_FILE ?= ENVIRONMENT.md

# GO_FERRITE_BINARY is the path to the binary that is used to generate the
# Ferrite documentation.
GO_FERRITE_BINARY ?= $(GO_DEBUG_DIR)/$(_GO_COMMAND_PACKAGES)

GENERATED_FILES += $(GO_FERRITE_MARKDOWN_FILE)
_CI_VERIFY_GENERATED_FILES_ALWAYS += $(GO_FERRITE_MARKDOWN_FILE)

$(GO_FERRITE_MARKDOWN_FILE): $(GO_FERRITE_BINARY)
	FERRITE_MODE=usage/markdown $(GO_FERRITE_BINARY) > $@
